[base]
package = stonks
env_name = stonks
policy_name = Policy
rnn_name = Recurrent
vec = multiprocessing
#vec = serial

#[env]
#num_envs = 128 

[train]
total_timesteps = 100_000_000

num_envs =  1
num_workers = 1
env_batch_size = 1
batch_size = 65536

; num_envs =  1024
; num_workers = 8
; env_batch_size = 512
; batch_size = 65536
gamma = 0.95

[sweep]
method = protein
name = sweep

[sweep.metric]
goal = maximize
name = score 
min = 0
max = 864

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e7
max = 1e8
mean = 5e7
scale = auto
